force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <label>Attendance</label>
    <nameField>
        <displayFormat>ATD-{0000}</displayFormat>
        <label>Attendance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>SFDC_Class__c</referenceTo>
    <relationshipLabel>Attendance</relationshipLabel>
    <relationshipName>Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <formula>Class__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Class ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Class_Type__c.field-meta.xml
<CustomField>
    <fullName>Class_Type__c</fullName>
    <label>Class Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Make-up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/CNA_Hours_number__c.field-meta.xml
<CustomField>
    <fullName>CNA_Hours_number__c</fullName>
    <label>CNA Hours in number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/CNA_Minutes_in_number__c.field-meta.xml
<CustomField>
    <fullName>CNA_Minutes_in_number__c</fullName>
    <label>CNA Minutes in number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/CNA_Training__c.field-meta.xml
<CustomField>
    <fullName>CNA_Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CNA Training</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Roaster__c</field>
            <operation>equals</operation>
            <valueField>CNA_Training__c.Roster__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CNA_Training__c</referenceTo>
    <relationshipLabel>Attendance</relationshipLabel>
    <relationshipName>Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Attendance</relationshipLabel>
    <relationshipName>Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <formula>Contact__r.FirstName + &apos; &apos;+  Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Class Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Enrollment__c</fullName>
    <label>Enrollment</label>
    <referenceTo>SFDC_Enrollment__c</referenceTo>
    <relationshipLabel>Attendance</relationshipLabel>
    <relationshipName>Attendance</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Has_Make_Up_Class__c.field-meta.xml
<CustomField>
    <fullName>Has_Make_Up_Class__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field has created to find the Attendance records that&apos;s belong to Make-Up Class for Students.</description>
    <label>Belongs to MakeUp Class?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/hours_rolledUp__c.field-meta.xml
<CustomField>
    <fullName>hours_rolledUp__c</fullName>
    <defaultValue>false</defaultValue>
    <label>hours_rolledUp?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Makeup_Class_status__c.field-meta.xml
<CustomField>
    <fullName>Makeup_Class_status__c</fullName>
    <label>Makeup Class status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Absent</fullName>
            </value>
            <value>
                <fullName>Attended regular class</fullName>
            </value>
            <value>
                <fullName>Attended make-up class</fullName>
            </value>
            <value>
                <fullName>Need to attend make-up class</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Roaster__c.field-meta.xml
<CustomField>
    <fullName>Roaster__c</fullName>
    <label>Roster</label>
    <referenceTo>Roaster__c</referenceTo>
    <relationshipLabel>Attendance</relationshipLabel>
    <relationshipName>Attendance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Roaster_No__c.field-meta.xml
<CustomField>
    <fullName>Roaster_No__c</fullName>
    <formula>Roaster__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Roster ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Attendance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Absent</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Present-Make up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Students_RSVP__c.field-meta.xml
<CustomField>
    <fullName>Students_RSVP__c</fullName>
    <label>Students RSVP</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting RSVP</fullName>
                <default>true</default>
                <label>Awaiting RSVP</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Maybe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CNA_Training__c/CNA_Training__c.object-meta.xml
<CustomObject>
    <label>CNA Training</label>
    <nameField>
        <displayFormat>CNA-{0000}</displayFormat>
        <label>CNA Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNA Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CNA_Training__c/fields/Class_Type__c.field-meta.xml
<CustomField>
    <fullName>Class_Type__c</fullName>
    <inlineHelpText>Choose whether CNA hours marked is for Regular class or Makeup class</inlineHelpText>
    <label>Class Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Make-up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CNA_Training__c/fields/Duration_of_Class__c.field-meta.xml
<CustomField>
    <fullName>Duration_of_Class__c</fullName>
    <inlineHelpText>Duration of Class field helps us to calculate the overall duration of the Session and it will count duration update to Roster and Enrollments as well.</inlineHelpText>
    <label>Duration of Class</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CNA_Training__c/fields/Roster__c.field-meta.xml
<CustomField>
    <fullName>Roster__c</fullName>
    <label>Roster</label>
    <referenceTo>Roaster__c</referenceTo>
    <relationshipLabel>CNA Trainings</relationshipLabel>
    <relationshipName>CNA_Trainings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Enrolled in a Class</fullName>
                <isActive>false</isActive>
                <label>Enrolled in a Class</label>
            </value>
            <value>
                <fullName>Not Interested</fullName>
                <isActive>false</isActive>
                <label>Not Interested</label>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
                <isActive>false</isActive>
                <label>Not Qualified</label>
            </value>
            <value>
                <fullName>Ongoing_Assessment</fullName>
                <isActive>false</isActive>
                <label>Ongoing Assessment</label>
            </value>
            <value>
                <fullName>Provider Participation Form Submitted</fullName>
                <isActive>false</isActive>
                <label>Provider Participation Form Submitted</label>
            </value>
            <value>
                <fullName>Qualified As Provider</fullName>
                <isActive>false</isActive>
                <label>Qualified As Provider</label>
            </value>
            <value>
                <fullName>Recruited</fullName>
                <isActive>false</isActive>
                <label>Recruited</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roaster__c/Roaster__c.object-meta.xml
<CustomObject>
    <label>Class Session</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Roaster__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <referenceTo>SFDC_Class__c</referenceTo>
    <relationshipName>Roasters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Roaster__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Need to create Make-Up</fullName>
            </value>
            <value>
                <fullName>Make-Up Ongoing</fullName>
            </value>
            <value>
                <fullName>Make-Up not Required</fullName>
            </value>
            <value>
                <fullName>Make-Up Class Completed</fullName>
                <isActive>false</isActive>
                <label>Make-Up Class Completed</label>
            </value>
            <value>
                <fullName>MakeUp Class</fullName>
                <isActive>false</isActive>
                <label>MakeUp Class</label>
            </value>
            <value>
                <fullName>Postponed</fullName>
                <isActive>false</isActive>
                <label>Postponed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Roaster__c/fields/Students_RSVP__c.field-meta.xml
<CustomField>
    <fullName>Students_RSVP__c</fullName>
    <label>Students RSVP</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Maybe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_Class__c/SFDC_Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_Class__c/fields/Class_type__c.field-meta.xml
<CustomField>
    <fullName>Class_type__c</fullName>
    <label>Instructor 1 Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Part Time</fullName>
            </value>
            <value>
                <fullName>Full Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Hours_Duration_Update.cls
public class Hours_Duration_Update {
    
    public void calculate_hours(List<CNA_Training__c> cna_id){
        
        Map<Id, CNA_Training__c > cna_map = new Map<Id, CNA_Training__c>([select id, Name, Class_Type__c ,Duration_of_Class__c , Roster__c From CNA_Training__c where id=:cna_id]);
        system.debug('cna_map are '+cna_map);  
        
        set<Id> roster_Id = new set<Id>();
        string cnaId = '';
        
        for(CNA_Training__c c :cna_map.values()){
            roster_Id.add(c.Roster__c);
            cnaId = string.valueOf(c.id);
        }
        system.debug('roster_Id are '+roster_Id);
        
        system.debug('cnaId are '+cnaId);
            
        system.debug('cna_map ids are '+cna_map.get('id'));
        system.debug('cna_map values are '+cna_map.values());
        system.debug('cna_map Keyset() are '+cna_map.values());
        
        
        
        List<Attendance__c > att_recs = [select id, name, CNA_Training__c, Students_RSVP__c,CNA_Hours_number__c,CNA_Minutes_in_number__c, createdDate, hours_rolledUp__c, Class_Type__c,  Class_Name__c, Makeup_Class_status__c, Roaster_No__c, Contact_Name__c, Class__c, Class__r.id, Class__r.Name, Contact__c, Contact__r.id, Contact__r.Name, Date__c, Enrollment__c, Roaster__c, Roaster__r.id, Status__c, Has_Make_Up_Class__c from Attendance__c where Roaster__r.id=:roster_Id and Status__c ='Present'];
        system.debug('att_recs are '+att_recs); 
        system.debug('att_recs size are '+att_recs.size()); 
        for(Attendance__c a:  att_recs){
            if(a.CNA_Training__c <> null ){
                //a.CNA_Training__c = cnaId;
            }
            
        }
        
        //Update att_recs;
        system.debug('att_recs are '+att_recs);
        
    }       
}