force-app/main/default/objects/Instructor__c/Instructor__c.object-meta.xml
<CustomObject>
    <label>Instructor</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Faculty ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instructors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Instructor__c/fields/Available_Friday__c.field-meta.xml
<CustomField>
    <fullName>Available_Friday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available Friday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Instructor__c/fields/Available_Monday__c.field-meta.xml
<CustomField>
    <fullName>Available_Monday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available Monday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Instructor__c/fields/Available_Saturday__c.field-meta.xml
<CustomField>
    <fullName>Available_Saturday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available Saturday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Instructor__c/fields/Available_Thursday__c.field-meta.xml
<CustomField>
    <fullName>Available_Thursday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available Thursday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Instructor__c/fields/Available_Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Available_Tuesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available Tuesday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Instructor__c/fields/Available_Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Available_Wednesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available Wednesday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Instructor__c/fields/Friday_Available_Time__c.field-meta.xml
<CustomField>
    <fullName>Friday_Available_Time__c</fullName>
    <label>Friday Available Time</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>9:00 AM - 10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM - 11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM - 12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:00 PM - 1:00 PM</fullName>
            </value>
            <value>
                <fullName>1:00 PM - 2:00 PM</fullName>
            </value>
            <value>
                <fullName>2:00 PM - 3:00 PM</fullName>
            </value>
            <value>
                <fullName>3:00 PM - 4:00 PM</fullName>
            </value>
            <value>
                <fullName>4:00 PM - 5:00 PM</fullName>
            </value>
            <value>
                <fullName>5:00 PM - 6:00 PM</fullName>
            </value>
            <value>
                <fullName>6:00 PM - 7:00 PM</fullName>
            </value>
            <value>
                <fullName>7:00 PM - 8:00 PM</fullName>
            </value>
            <value>
                <fullName>8:00 PM - 9:00 PM</fullName>
            </value>
            <value>
                <fullName>9:00 PM - 10:00 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Instructor__c/fields/Monday_Available_time__c.field-meta.xml
<CustomField>
    <fullName>Monday_Available_time__c</fullName>
    <label>Monday Available Time</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>9:00 AM - 10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM - 11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM - 12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:00 PM - 1:00 PM</fullName>
            </value>
            <value>
                <fullName>1:00 PM - 2:00 PM</fullName>
            </value>
            <value>
                <fullName>2:00 PM - 3:00 PM</fullName>
            </value>
            <value>
                <fullName>3:00 PM - 4:00 PM</fullName>
            </value>
            <value>
                <fullName>4:00 PM - 5:00 PM</fullName>
            </value>
            <value>
                <fullName>5:00 PM - 6:00 PM</fullName>
            </value>
            <value>
                <fullName>6:00 PM - 7:00 PM</fullName>
            </value>
            <value>
                <fullName>7:00 PM - 8:00 PM</fullName>
            </value>
            <value>
                <fullName>8:00 PM - 9:00 PM</fullName>
            </value>
            <value>
                <fullName>9:00 PM - 10:00 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Instructor__c/fields/Thursday_Available_Time__c.field-meta.xml
<CustomField>
    <fullName>Thursday_Available_Time__c</fullName>
    <label>Thursday Available Time</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>9:00 AM - 10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM - 11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM - 12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:00 PM - 1:00 PM</fullName>
            </value>
            <value>
                <fullName>1:00 PM - 2:00 PM</fullName>
            </value>
            <value>
                <fullName>2:00 PM - 3:00 PM</fullName>
            </value>
            <value>
                <fullName>3:00 PM - 4:00 PM</fullName>
            </value>
            <value>
                <fullName>4:00 PM - 5:00 PM</fullName>
            </value>
            <value>
                <fullName>5:00 PM - 6:00 PM</fullName>
            </value>
            <value>
                <fullName>6:00 PM - 7:00 PM</fullName>
            </value>
            <value>
                <fullName>7:00 PM - 8:00 PM</fullName>
            </value>
            <value>
                <fullName>8:00 PM - 9:00 PM</fullName>
            </value>
            <value>
                <fullName>9:00 PM - 10:00 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Instructor__c/fields/Tuesday_Available_Time__c.field-meta.xml
<CustomField>
    <fullName>Tuesday_Available_Time__c</fullName>
    <label>Tuesday Available Time</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>9:00 AM - 10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM - 11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM - 12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:00 PM - 1:00 PM</fullName>
            </value>
            <value>
                <fullName>1:00 PM - 2:00 PM</fullName>
            </value>
            <value>
                <fullName>2:00 PM - 3:00 PM</fullName>
            </value>
            <value>
                <fullName>3:00 PM - 4:00 PM</fullName>
            </value>
            <value>
                <fullName>4:00 PM - 5:00 PM</fullName>
            </value>
            <value>
                <fullName>5:00 PM - 6:00 PM</fullName>
            </value>
            <value>
                <fullName>6:00 PM - 7:00 PM</fullName>
            </value>
            <value>
                <fullName>7:00 PM - 8:00 PM</fullName>
            </value>
            <value>
                <fullName>8:00 PM - 9:00 PM</fullName>
            </value>
            <value>
                <fullName>9:00 PM - 10:00 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Instructor__c/fields/Wednesday_Available_Time__c.field-meta.xml
<CustomField>
    <fullName>Wednesday_Available_Time__c</fullName>
    <label>Wednesday Available Time</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>9:00 AM - 10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM - 11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM - 12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:00 PM - 1:00 PM</fullName>
            </value>
            <value>
                <fullName>1:00 PM - 2:00 PM</fullName>
            </value>
            <value>
                <fullName>2:00 PM - 3:00 PM</fullName>
            </value>
            <value>
                <fullName>3:00 PM - 4:00 PM</fullName>
            </value>
            <value>
                <fullName>4:00 PM - 5:00 PM</fullName>
            </value>
            <value>
                <fullName>5:00 PM - 6:00 PM</fullName>
            </value>
            <value>
                <fullName>6:00 PM - 7:00 PM</fullName>
            </value>
            <value>
                <fullName>7:00 PM - 8:00 PM</fullName>
            </value>
            <value>
                <fullName>8:00 PM - 9:00 PM</fullName>
            </value>
            <value>
                <fullName>9:00 PM - 10:00 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Instructor_Course__c/Instructor_Course__c.object-meta.xml
<CustomObject>
    <label>Instructor Course</label>
    <nameField>
        <label>Instructor Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instructor Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Instructor_Course__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <label>Instructor</label>
    <referenceTo>Instructor__c</referenceTo>
    <relationshipLabel>Instructor Courses</relationshipLabel>
    <relationshipName>Instructor_Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Instructor_Course__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Instructor Courses</relationshipLabel>
    <relationshipName>Instructor_Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_Class__c/SFDC_Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_Class__c/fields/Class_Status__c.field-meta.xml
<CustomField>
    <fullName>Class_Status__c</fullName>
    <label>Class Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Upcoming</fullName>
                <default>true</default>
                <label>Upcoming</label>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_Class__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <label>Days</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mon</fullName>
            </value>
            <value>
                <fullName>Tue</fullName>
            </value>
            <value>
                <fullName>Wed</fullName>
            </value>
            <value>
                <fullName>Thu</fullName>
            </value>
            <value>
                <fullName>Fri</fullName>
            </value>
            <value>
                <fullName>Sat</fullName>
            </value>
            <value>
                <fullName>Sun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_Class__c/fields/Instructor_ID_2__c.field-meta.xml
<CustomField>
    <fullName>Instructor_ID_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instructor ID 2</label>
    <referenceTo>Instructor__c</referenceTo>
    <relationshipLabel>Classes (Instructor ID 2)</relationshipLabel>
    <relationshipName>Classes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_Class__c/fields/Instructor_ID__c.field-meta.xml
<CustomField>
    <fullName>Instructor_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instructor ID 1</label>
    <referenceTo>Instructor__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_Class__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LookupPopupController.cls
// Custom controller for lookup popup page
public with sharing class LookupPopupController {
  public String query {get; set;}
  public string objectName {get; set;}
  public List<SObject> records {get; set;}
  public list<string> fields {get; set;} 
  
  public LookupPopupController() {
    runQuery();
  }
   
  public PageReference runQuery() {
    string fieldName = ApexPages.currentPage().getParameters().get('namefield');
    system.debug('Field Name : ' + fieldName);
    fields = fieldName == 'location' ? new list<string>{'Classroom_Name__c', 'Capacity__c'} 
                                        : new list<string>{'First_Name__c', 'Last_Name__c', 'Email_Address__c'};
    objectName = fieldName == 'location' ? 'Locations__c' : 'Instructor__c';//Instructor__c 
    string ins1 = ApexPages.currentPage().getParameters().get('instructor1');
    string ins2 = ApexPages.currentPage().getParameters().get('instructor2');
    string classDays = ApexPages.currentPage().getParameters().get('Days');
    string classTime = ApexPages.currentPage().getParameters().get('classTime');
    string course = ApexPages.currentPage().getParameters().get('course');
    string capacity = ApexPages.currentPage().getParameters().get('capacity');
    
    system.debug('Class Time : ' + classTime);
    if(string.isNotBlank(classTime)) {
      string timeRegExp = '([0-1]?[0-9]:[0-9][0-9] [A|P]M)';
      Pattern MyPattern = Pattern.compile(timeRegExp);
      Matcher MyMatcher = MyPattern.matcher(classTime);
      if(!MyMatcher.matches()) { 
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please make sure that the Class time\'s format is \"HH:MM AM/PM - HH:MM AM/PM\"'));
        return null;
      } 
    } 
    
    set<string> days = string.isNotEmpty(classDays) ? new set<string>(classDays.split(',')) : new set<string>();
    string classTiming = '';
    if(string.isNotBlank(classTime)) {
      Integer sh = Integer.valueOf(classTime.substringBefore('-').trim().substringBefore(':'));
      Integer eh = Integer.valueOf(classTime.substringAfter('-').trim().substringBefore(':'));
      string sm = classTime.substringBefore('-').trim().substringAfter(':').substringBefore(' ');
      string em = classTime.substringAfter('-').trim().substringAfter(':').substringBefore(' ');
      string t = classTime.substringBefore('-').trim().substringAfter(' ');
      system.debug('Start Hour : ' + sh + '\nEnd Hour : ' + eh + '\nAM/PM : ' + t);
      for(Integer i = sh; i < (sh == eh ? sh+12 : (sh > eh && t == 'PM' ? eh+12 : eh)); i++) {
        classTiming += (i < 13 ? i : i - 12) + ':' + sm + ' ' + (t == 'AM' ? (i < 12 ? t : 'PM') : t) + ' - ' 
                       + (i < 12 ? i + 1 : i - 11) + ':' + sm + ' ' + (t == 'AM' ? (i < 11 ? t : 'PM') : t);
        if(i < (eh  - 1))
          classTiming += ';';
      }
      system.debug('Class Timing : ' + classTiming);
    }
    string searchquery = '';
    if(fieldName == 'location') {
      searchQuery = query != null ? 'FIND :query IN ALL FIELDS RETURNING Locations__c (Id, Name, Classroom_Name__c, Capacity__c where Active__c = true and Byteback_Location__c = true'
                                  : 'select Id, Name, Classroom_Name__c, Capacity__c from Locations__c where Active__c = true and Byteback_Location__c = true';
      if(String.isNotBlank(capacity))                            
        searchQuery += (searchQuery.contains('where') ? ' and '  : ' where ') + 'Capacity__c >= ' + Integer.valueOf(capacity);
    }
    else {
      searchQuery = query != null ? 'FIND :query IN ALL FIELDS RETURNING Instructor__c (Id, Name, First_Name__c, Last_Name__c, Email__c where Active__c = true'
                                  : 'select Id, Name, First_Name__c, Last_Name__c, Email__c from Instructor__c where Active__c = true';
      if(String.isNotBlank(ins1)) 
        searchQuery += (searchQuery.contains('where') ? ' and '  : ' where ') + 'Id !=: ins1';
      if(String.isNotBlank(ins2))
        searchQuery += (searchQuery.contains('where') ? ' and ' : ' where ') + 'Id !=: ins2';      
      if(String.isNotBlank(course)) {
        set<Id> instIds = new set<Id>();
        for(Instructor_Course__c ic : [select Instructor__c from Instructor_Course__c where Product__r.Name =: course])
          instIds.add(ic.Instructor__c);
        searchquery += (searchQuery.contains('where') ? ' and ' : ' where ') + 'Id IN: instIds';
      }
    }
    if(!days.isEmpty()) {
      list<string> daysList = new list<string>(days);
      string dayString = '\'' + daysList[0] + '\'';
      for(Integer i = 1; i < daysList.size(); i++)
        dayString += ',\'' + daysList[i] + '\'';
        
      system.debug('Day String : ' + dayString);  
      
      searchQuery += (searchQuery.contains('where') ? ' and ' : ' where ') 
                     + 'Id NOT IN (select ' + (fieldName == 'location' ? 'Location__c' : 'Instructor_ID__c') 
                     + ' from SFDC_Class__c where Days__c IN (' + dayString 
                     + ') and (Class_Status__c = \'Upcoming\' or Class_Status__c = \'Registering\' or Class_Status__c = \'Ongoing\')';
      searchQuery += string.isNotBlank(classTime) ? ' and Start_Time__c =: classTime)' : ')';   
      if(fieldName != 'location') { 
        searchQuery += (searchQuery.contains('where') ? ' and ' : ' where ') 
                       + 'Id NOT IN (select Instructor_ID_2__c from SFDC_Class__c where Days__c IN ('
                       + dayString + ') and (Class_Status__c = \'Upcoming\' or Class_Status__c = \'Registering\' or Class_Status__c = \'Ongoing\')';     
        searchQuery += string.isNotBlank(classTime) ? ' and Start_Time__c =: classTime)' : ')';    
      }
        
      if(days.contains('Mon')) {
        searchQuery += (searchQuery.contains('where') ? ' and ' : ' where ') + 'Available_Monday__c = true';
        if(string.isNotBlank(classTime)) 
          searchQuery += ' and Monday_Available_time__c IN (\'' + classTiming + '\')';                    
      }
      if(days.contains('Tue')) {
        searchQuery += (searchQuery.contains('where') ? ' and ' : ' where ') + 'Available_Tuesday__c = true';
        if(string.isNotBlank(classTime))
          searchQuery += ' and Tuesday_Available_time__c IN (\'' + classTiming + '\')'; 
      }
      if(days.contains('Wed')) {
        searchQuery += (searchQuery.contains('where') ? ' and ' : ' where ') + 'Available_Wednesday__c = true';
        if(string.isNotBlank(classTime))
          searchQuery += ' and Wednesday_Available_time__c IN (\'' + classTiming + '\')'; 
      }
      if(days.contains('Thu')) {
        searchQuery += (searchQuery.contains('where') ? ' and ' : ' where ') + 'Available_Thursday__c = true';
        if(string.isNotBlank(classTime))
          searchQuery += ' and Thursday_Available_time__c IN (\'' + classTiming + '\')'; 
      }
      if(days.contains('Fri')) {
        searchQuery += (searchQuery.contains('where') ? ' and ' : ' where ') + 'Available_Friday__c = true';         
        if(string.isNotBlank(classTime))
          searchQuery += ' and Friday_Available_time__c IN (\'' + classTiming + '\')'; 
      }
      if(days.contains('Sat')) {
        searchQuery += (searchQuery.contains('where') ? ' and ' : ' where ') + 'Available_Saturday__c = true';         
        if(string.isNotBlank(classTime))
          searchQuery += ' and Saturday_Available_time__c IN (\'' + classTiming + '\')'; 
      }
       
    }  
    searchQuery += query != null ? ')' : (searchQuery.contains('where') ? ' order by Name asc limit 10' 
                                          : ' where LastViewedDate != null order by LastViewedDate desc limit 10');
    system.debug('Query: ' + searchQuery);
    records = query != null ? search.query(searchquery)[0] : Database.query(searchQuery);
    return null;
  }
}