force-app/main/default/objects/Contact/fields/AD8Check__c.field-meta.xml
<CustomField>
    <fullName>AD8Check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AD8Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Consumer_Participation_form_submitted__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Participation_form_submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Consumer Participation form submitted?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Participation_form_submitted__c.field-meta.xml
<CustomField>
    <fullName>Participation_form_submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Provider Participation form submitted?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SQCheck__c.field-meta.xml
<CustomField>
    <fullName>SQCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SQCheck</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IconsForContact1.cls
public class IconsForContact1 {
    public contact conrec {get;set;}
    public string accId {get;set;}
    public String contId {get;set;}
    public IconsForContact1 (ApexPages.StandardController controller){
        contId =controller.getRecord().id;

        system.debug('contId===='+contId);
        conrec= new contact();
        if(contId!=null){
 
        conrec= [Select id,Last_Name__c,SQCheck__c,AD8Check__c,Participation_form_submitted__c,Consumer_Participation_form_submitted__c
                 from contact where id=:ApexPages.currentPage().getParameters().get('id')];
        system.debug('Id:'+conrec);
                        }}
                           }