force-app/main/default/objects/SFDC_Class__c/SFDC_Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_Enrollment__c/SFDC_Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000}</displayFormat>
        <label>Enrollment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_Enrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>SFDC_Class__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SFDC_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_Enrollment__c/fields/Final_Assessment_Score1__c.field-meta.xml
<CustomField>
    <fullName>Final_Assessment_Score1__c</fullName>
    <label>GPA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SFDC_Enrollment__c/fields/Mid_Point_Assessment_Score__c.field-meta.xml
<CustomField>
    <fullName>Mid_Point_Assessment_Score__c</fullName>
    <label>Credit Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SFDC_Enrollment__c/fields/Pass_DNP__c.field-meta.xml
<CustomField>
    <fullName>Pass_DNP__c</fullName>
    <label>Pass/DNP</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DNP</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Enrollment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enrolled</fullName>
                <default>true</default>
                <label>Enrolled</label>
            </value>
            <value>
                <fullName>Student Requested for Removal</fullName>
            </value>
            <value>
                <fullName>Student Requested for Transfer</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>1-DAY</fullName>
                <isActive>false</isActive>
                <label>1-DAY</label>
            </value>
            <value>
                <fullName>No Show</fullName>
                <isActive>false</isActive>
                <label>No Show</label>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
                <isActive>false</isActive>
                <label>Not Applicable</label>
            </value>
            <value>
                <fullName>Registered</fullName>
                <isActive>false</isActive>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Waiting</fullName>
                <isActive>false</isActive>
                <label>Waiting</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AddEnrollments.cls
public class AddEnrollments {


        public SFDC_Class__c Classes;
        public SFDC_Enrollment__c del;
        public List < SFDC_Enrollment__c > addEnrollmentList {get;set;}
        public List < SFDC_Enrollment__c > delEnrollmentList {get;set;}
        public List < SFDC_Enrollment__c > EnrollmentList {get;set;}
        public Integer totalCount {get;set;}
        public Integer rowIndex {get;set;}
        public List < SFDC_Enrollment__c > delEnrollments {get;set;}
        public Id ClassId = ApexPages.currentPage().getParameters().get('id');
        public AddEnrollments(ApexPages.StandardSetController controller) {
           // Classes = (SFDC_Class__c) controller.getRecord();
                EnrollmentList = [SELECT Id,name,Status__c,Class__c,Contact__c,Pass_DNP__c,Mid_Point_Assessment_Score__c,Final_Assessment_Score1__c FROM SFDC_Enrollment__c where Class__c = :ClassId];
                totalCount = EnrollmentList.size();
                delEnrollmentList = new List < SFDC_Enrollment__c > ();
                delEnrollments = new List < SFDC_Enrollment__c > ();
        }

       /* public void addRow() {
                addEnrollmentList = new List < SFDC_Enrollment__c > ();
                EnrollmentList.add(new SFDC_Enrollment__c(Class__c = ClassId));
        }*/

        public PageReference save() {
                upsert EnrollmentList;
                delete delEnrollmentList;
                //return (new ApexPages.StandardController(Classs)).view();

      /*PageReference secondPage = new PageReference(ApexPages.currentPage().getParameters().get('retURL'));  
      secondPage.setRedirect(true);
      return secondPage;*/ 
        System.debug('the class id is'+ClassId);
               PageReference pageRef = new PageReference('/'+ClassId);
               //pageRef.getParameters().put('id',Classes.Id);
               pageRef.setRedirect(true);
               return pageRef;  
        }
        public void deleteRow() {
                rowIndex = Integer.valueOf(ApexPages.currentPage().getParameters().get('rowIndex'));
                del = EnrollmentList.remove(rowIndex);
                delEnrollmentList.add(del);
        }
}